import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "./components/Footer";

import HeroSection from "./components/HeroSection";
import TopBar from "./components/TopBar";
import Products1 from "./components/F-Products";
import Navbar1 from "./components/Header1";
import LeatestBlog from "./components/LeatestBlog";
import { Hero2 } from "./components/Hero2";
// import OneMore from "./components/12";
import TrendingProducts from "./components/TrendingProducts";



// import MyAccount12 from "./components/12";
// import TrendingProducts from "./components/12";











const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <TopBar />
        {/* <Header1/> */}
        
        <Navbar1 />
        <HeroSection />
        <Products1 />
        {/* <TrendingProducts/> */}
        <Hero2/>
        <TrendingProducts/>
        
        <LeatestBlog/>
        
        <Footer />
        
        {/* <OneMore/> */}
        
        
        
        
       










        {children}
      </body>
    </html>
  );
}
